# Generated by Django 5.2.4 on 2025-10-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='appliedStudents',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
