# Generated by Django 5.2.4 on 2025-10-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_registration_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_or_college_registration',
            old_name='school_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='school_or_college_registration',
            old_name='principal_name',
            new_name='principal',
        ),
        migrations.RemoveField(
            model_name='school_or_college_registration',
            name='eoi_letter',
        ),
        migrations.AddField(
            model_name='school_or_college_registration',
            name='eol_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/eoi_letters/'),
        ),
        migrations.AddField(
            model_name='school_or_college_registration',
            name='password',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
