# Generated by Django 5.2.4 on 2025-10-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_school_name_school_or_college_registration_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_registration',
            name='category',
            field=models.CharField(default='Private', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer_registration',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/Employer/certificate/'),
        ),
        migrations.AddField(
            model_name='employer_registration',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer_registration',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer_registration',
            name='eoiLetter',
            field=models.FileField(blank=True, null=True, upload_to='documents/Employer/eoi/'),
        ),
        migrations.AddField(
            model_name='employer_registration',
            name='gstNumber',
            field=models.CharField(default='GST000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer_registration',
            name='irn',
            field=models.CharField(default='IRN000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer_registration',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer_registration',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employer_registration',
            name='enrollment',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
