# Generated by Django 5.2.4 on 2025-10-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_employer_registration_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officials_registration',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
