# Generated by Django 5.2.4 on 2025-10-28 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_officials_registration_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False)),
                ('confirmed_interview', models.BooleanField(default=False)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending School Approval', 'Pending School Approval'), ('Approved by School', 'Approved by School'), ('Rejected by School', 'Rejected by School'), ('Approved by Employer', 'Approved by Employer'), ('Rejected by Employer', 'Rejected by Employer'), ('Interview Confirmed', 'Interview Confirmed')], default='Pending School Approval', max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student_registration')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vacancy')),
            ],
        ),
    ]
