# Generated by Django 5.2.4 on 2025-10-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_jobapplication_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_or_college_registration',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school_or_college_registration',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
