# Generated by Django 5.2.4 on 2025-10-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_school_or_college_registration_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_registration',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer_registration',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
