# Generated by Django 5.2.6 on 2025-11-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_employer_registration_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SCHOOL_OR_COLLEGE_REGISTRATION',
            new_name='SchoolRegistration',
        ),
        migrations.DeleteModel(
            name='Commission_Registration',
        ),
        migrations.DeleteModel(
            name='Company_Registration',
        ),
    ]
